// Generated by @x402/extensions declareDiscoveryExtension — x402 Bazaar discovery metadata
export default {
 "/analyze": {
  "bazaar": {
   "info": {
    "input": {
     "type": "http",
     "bodyType": "json",
     "body": {
      "noticeId": "a1b2c3d4e5f6",
      "companyProfile": "Small 8(a) IT firm, cloud migration, DoD experience"
     }
    },
    "output": {
     "type": "json",
     "example": {
      "ok": true,
      "score": 72,
      "recommendation": "BID",
      "strengths": [
       "NAICS match"
      ],
      "risks": [
       "Incumbent advantage"
      ],
      "competition": "medium",
      "summary": "Strong fit..."
     }
    }
   },
   "schema": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
     "input": {
      "type": "object",
      "properties": {
       "type": {
        "type": "string",
        "const": "http"
       },
       "method": {
        "type": "string",
        "enum": [
         "POST",
         "PUT",
         "PATCH"
        ]
       },
       "bodyType": {
        "type": "string",
        "enum": [
         "json",
         "form-data",
         "text"
        ]
       },
       "body": {
        "properties": {
         "noticeId": {
          "type": "string",
          "description": "SAM.gov notice ID (get free via /search or MCP search_opportunities)"
         },
         "companyProfile": {
          "type": "string",
          "description": "Optional 1-3 sentence bidder profile"
         }
        },
        "required": [
         "noticeId"
        ]
       }
      },
      "required": [
       "type",
       "method",
       "bodyType",
       "body"
      ],
      "additionalProperties": false
     },
     "output": {
      "type": "object",
      "properties": {
       "type": {
        "type": "string"
       },
       "example": {
        "type": "object"
       }
      },
      "required": [
       "type"
      ]
     }
    },
    "required": [
     "input"
    ]
   }
  }
 }
};
